#kubectl create secret docker-registry regcred --docker-server=https://index.docker.io/v1/ --docker-username=<username-docker> --docker-password=<senha-docker> --docker-email=<email-docker>
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: bragapets
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: app
      labels:
        app: app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: app
          image: rickalbbraga/bragapets:latest
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 80
          #   initialDelaySeconds: 60
          #   periodSeconds: 15
          #   failureThreshold: 3
          #   successThreshold: 1
          # readinessProbe:
          #   httpGet:
          #     path: /ready
          #     port: 80
          #   initialDelaySeconds: 15
          #   timeoutSeconds: 15
          #   periodSeconds: 10
          #   successThreshold: 2
          #   failureThreshold: 1
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: app-cm
            - secretRef:
                name: app-sc
  