apiVersion: apps/v1
kind: Deployment
metadata:
  name: bragapets-app
  namespace: bragapets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bragapets-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: bragapets-app
      labels:
        app: bragapets-app
    spec:
      imagePullSecrets:
        - name: regcred
      # nodeSelector:
      #   nome-label-definido: valor-label-definido
      containers:
        - name: bragapets-app
          image: rickalbbraga/bragapets:latest
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS 
              value: http://+:80
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 80
          #   initialDelaySeconds: 60
          #   periodSeconds: 15
          #   failureThreshold: 3
          #   successThreshold: 1
          # readinessProbe:
          #   httpGet:
          #     path: /ready
          #     port: 80
          #   initialDelaySeconds: 15
          #   timeoutSeconds: 15
          #   periodSeconds: 10
          #   successThreshold: 2
          #   failureThreshold: 1
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          # envFrom:
          #   - configMapRef:
          #       name: usersapp-cm
          #   - secretRef:
          #       name: usersapp-sc
  