#kubectl label nodes <nome-do-seu-node> <nome-label-desejado=valor-label> 
#kubectl create secret docker-registry regcred --docker-server=https://index.docker.io/v1/ --docker-username=<user-docker> --docker-password=<senha-docker> --docker-email=<emaail-docker>
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usersapp-dp
  namespace: bragapets
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bragapets-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: bragapets-app
      labels:
        app: bragapets-app
    spec:
      # imagePullSecrets:
      # - name: regcred
      # nodeSelector:
      #   nome-label-definido: valor-label-definido
      containers:
        - name: bragapets-app
          image: rickalbbraga/bragapets:latest
          # env:
          #   - name: SqlServer
          #     value: Server=mssql-svc-cip,1433;Database=rabraga;User Id=sa;Password=sqlserverk8sHml
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 80
          #   initialDelaySeconds: 60
          #   periodSeconds: 15
          #   failureThreshold: 3
          #   successThreshold: 1
          # readinessProbe:
          #   httpGet:
          #     path: /ready
          #     port: 80
          #   initialDelaySeconds: 15
          #   timeoutSeconds: 15
          #   periodSeconds: 10
          #   successThreshold: 2
          #   failureThreshold: 1
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          # envFrom:
          #   - configMapRef:
          #       name: usersapp-cm
          #   - secretRef:
          #       name: usersapp-sc
  