apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- secret.yaml
namespace: bragapets
images:
- name: app-image
  newName: rickalbbraga/bragapets
  newTag: ef0fab016cb7f0715a3ce1e76fe51d35faf577ed
