apiVersion: v1
kind: Service
metadata:
  name: bragapets-app-svc-cip
  namespace: bragapets
spec:
  selector:
    app: bragapets-app
  ports:
  - protocol: TCP
    port: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: bragapets-app-svc-np
  namespace: bragapets
spec:
  selector:
    app: bragapets-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000
  type: NodePort
