name: CI-CD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  USERNAME: rickalbbraga
  REPOSITORY: rickalbbraga/bragapets

jobs:
  build:
    name: Build App Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test
      - name: Build Image and Push to Dockerhub
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{env.USERNAME}}
          password: ${{secrets.CONTAINERREGISTRYTOKEN}} 
          repository: ${{env.REPOSITORY}}
          tags: ${{github.sha}}, latest
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: v3.6.1
      - name: Update Kustomization Yaml
        run: |
          cd k8s
          kustomize edit set image app-image=${{env.REPOSITORY}}:${{github.sha}}
          cat kustomization.yaml
      - name: Commit Yaml File
        run: |
          git config --local user.email "rickalbbraga@live.com"
          git config --local user.name "Deploy Action"
          git commit -am "change image tag"
      - name: Push File
        uses: ad-m/github-push-action@master  

